name: Deploy
on:
  push:
    branches: [ "master" ]
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - name: SSH into server and deploy
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USERNAME }}
          pass: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          connect_timeout: 10s
          script: |
            cd ~/fractals_api/
            git pull origin master 
            cargo build --release
            sudo systemctl restart fractals_api
